#!/bin/sh

echo "[universe]" | sudo tee -a /etc/pacman.conf
echo "Server = https://universe.artixlinux.org/$arch" | sudo tee -a /etc/pacman.conf
echo "Server = https://mirror1.artixlinux.org/universe/$arch" | sudo tee -a /etc/pacman.conf
echo "Server = https://mirror.pascalpuffke.de/artix-universe/$arch" | sudo tee -a /etc/pacman.conf
echo "Server = https://artixlinux.qontinuum.space/artixlinux/universe/os/$arch" | sudo tee -a /etc/pacman.conf
echo "Server = https://mirror1.cl.netactuate.com/artix/universe/$arch" | sudo tee -a /etc/pacman.conf
echo "Server = https://ftp.crifo.org/artix-universe/" | sudo tee -a /etc/pacman.conf
sudo pacman -S artix-archlinux-support

