#!/bin/bash

mkdir -p "$HOME"/.pixelfiles

# ------------ Installing Pacman Packages  ------------

# Installing Yay
git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
cd /tmp/yay-bin || return
makepkg -si
cd "$HOME" || return
rm -rf /tmp/yay-bin

# Installing Packages from the Arch Repos
sudo pacman -S xorg xorg-xinit python-pip python nitrogen conky lxsession-gtk3 zsh starship exa zoxide ranger pcmanfm cmus slock neovim shotgun hacksaw qutebrowser python-adblock wget curl mpv feh ttf-ubuntu-mono-nerd kvantum ttf-firacode-nerd unzip brightnessctl ttf-joypixels noto-fonts-cjk alsa-utils bat glow python-pywal xdotool

# Installing Packages from the AUR
yay -S network-manager-git papirus-icon-theme-git picom-jonaburg-git nordzy-cursors cli-visualizer ttf-sora nordic-bluish-accent-theme

# Installing Pip Packages
pip install inotify-simple python_daemon psutil python-prctl

# Installing Almarai Arabic Fonts
mkdir -p "$HOME"/.local/share/fonts
cd "$HOME"/.local/share/fonts || return
wget https://fonts.google.com/download?family=Almarai
unzip Almarai.zip
rm -rf Almari
cd "$HOME" || return

# ------------------ Cloning  Repos -------------------
git clone --recurse https://github.com/mohannadk28/dotfiles-pixelfiles "$HOME"/.pixelfiles/dotfiles-pixelfiles

git clone https://github.com/mohannadk28/wallpapers-pixelfiles "$HOME"/.pixelfiles/wallpapers-pixelfiles
git clone https://github.com/mohannadk28/scripts-pixelfiles "$HOME"/.pixelfiles/scripts-pixelfiles

git clone https://github.com/mohannadk28/sounds-pixelfiles "$HOME"/.pixelfiles/sounds-pixelfiles

# ------------ Building Suckless Software -------------

# Installing Dependences for Suckless Software
sudo pacman -S libx11 libxft harfbuzz

# DWM
git clone https://github.com/mohannadk28/dwm-pixelfiles "$HOME"/.pixelfiles/dwm-pixelfiles
cd "$HOME"/.pixelfiles/dwm-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# ST
git clone https://github.com/mohannadk28/st-pixelfiles "$HOME"/.pixelfiles/st-pixelfiles
cd "$HOME"/.pixelfiles/st-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# DWMBlocks
git clone https://github.com/mohannadk28/dwmblocks-pixelfiles "$HOME"/.pixelfiles/dwmblocks-pixelfiles
cd "$HOME"/.pixelfiles/dwmblocks-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# DMENU
git clone https://github.com/mohannadk28/dmenu-pixelfiles "$HOME"/.pixelfiles/dmenu-pixelfiles
cd "$HOME"/.pixelfiles/dmenu-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# ------------------ Symbolic Links -------------------

bash "$HOME"/.pixelfiles/dotfiles-pixelfiles/setup.sh
ln -sf "$HOME"/.pixelfiles/dwm-pixelfiles/.dwm "$HOME"/.local/share/dwm

# ---------------- Installing  Themes -----------------



# Installing MateriaNordDark
git clone https://github.com/tonyfettes/materia-nord-kvantum.git /tmp/materia-nord-kvantum 
sudo mv /tmp/materia-nord-kvantum/Kvantum/MateriaNordDark /usr/share/Kvantum
rm -rf /tmp/materia-nord-kvantum

