#!/bin/bash

mkdir -p "$HOME"/.pixelfiles

# ------------ Installing Pacman Packages  ------------

# Installing Yay
git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
cd /tmp/yay-bin || return
makepkg -si
cd "$HOME" || return
rm -rf /tmp/yay-bin

# Installing Packages from the Arch Repos
sudo pacman -S materia-gtk-theme libx11 libxft harfbuzz xorg xorg-xinit python-pip python nitrogen conky lxsession-gtk3 zsh starship exa zoxide ranger pcmanfm cmus slock neovim shotgun hacksaw qutebrowser python-adblock wget curl mpv feh ttf-ubuntu-mono-nerd kvantum ttf-firacode-nerd unzip brightnessctl ttf-joypixels noto-fonts-cjk alsa-utils bat glow python-pywal xdotool

# Installing Packages from the AUR
yay -S networkmanager-dmenu-git papirus-icon-theme-git picom-jonaburg-git cli-visualizer ttf-sora

# Installing Pip Packages
pip install inotify-simple python_daemon psutil python-prctl

# Installing Almarai Arabic Fonts
mkdir -p "$HOME"/.local/share/fonts
cd "$HOME"/.local/share/fonts || return
wget https://fonts.google.com/download?family=Almarai
unzip Almarai.zip
rm -rf Almari
cd "$HOME" || return

# ------------------ Cloning  Repos -------------------

git clone https://github.com/mohannadk28/scripts-pixelfiles "$HOME"/.pixelfiles/scripts-pixelfiles

# Config Files
git clone --recurse https://github.com/mohannadk28/dotfiles-pixelfiles "$HOME"/.pixelfiles/dotfiles-pixelfiles
git clone https://github.com/mohannadk28/nvim-pixelfiles "$HOME"/.pixelfiles/nvim-pixelfiles

# Assets
git clone https://github.com/mohannadk28/wallpapers-pixelfiles "$HOME"/.pixelfiles/wallpapers-pixelfiles
git clone https://github.com/mohannadk28/sounds-pixelfiles "$HOME"/.pixelfiles/sounds-pixelfiles

# Suckless Software
git clone https://github.com/mohannadk28/dwmblocks-pixelfiles "$HOME"/.pixelfiles/dwmblocks-pixelfiles
git clone https://github.com/mohannadk28/dmenu-pixelfiles "$HOME"/.pixelfiles/dmenu-pixelfiles
git clone https://github.com/mohannadk28/sxiv-pixelfiles "$HOME"/.pixelfiles/sxiv-pixelfiles
git clone https://github.com/mohannadk28/dwm-pixelfiles "$HOME"/.pixelfiles/dwm-pixelfiles
git clone https://github.com/mohannadk28/st-pixelfiles "$HOME"/.pixelfiles/st-pixelfiles

# ------------ Building Suckless Software -------------

# DWM
cd "$HOME"/.pixelfiles/dwm-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# ST
cd "$HOME"/.pixelfiles/st-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# DWMBlocks
cd "$HOME"/.pixelfiles/dwmblocks-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# DMENU
cd "$HOME"/.pixelfiles/dmenu-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# SXIV 
cd "$HOME"/.pixelfiles/sxiv-pixelfiles || return
sudo make clean install
cd "$HOME" || return

# ------------------ Symbolic Links -------------------

ln -sf "$HOME"/.pixelfiles/dwm-pixelfiles/.dwm "$HOME"/.local/share/dwm
ln -sf "$HOME"/.pixelfiles/nvim-pixelfiles "$HOME"/.config/nvim
ln -sf "$HOME"/.pixelfiles/sxiv-pixelfiles/.sxiv "$HOME"/.config/sxiv

bash "$HOME"/.pixelfiles/dotfiles-pixelfiles/setup.sh

# ----------------- Installing Neovim -----------------
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim -c "PackerSync"

